spring:
  datasource:
    url: jdbc:h2:file:~/data/h2/task
    driver-class-name: org.h2.Driver
    username: jack
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true